name: NPM Publish

on:
  push:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
        env:
            NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Whoami
        run: npm whoami
        env:
            NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test (coverage)
        run: npm run test:coverage

      - name: Test (mutation)
        run: npm run test:mutation

      - name: Configure GIT User
        run: |
          git config --global user.email "thomaschaplin@outlook.com"
          git config --global user.name "Thomas Chaplin"

      - name: Configure Legacy Auth Type
        run: npm config set auth-type=legacy

      - name: Publish
        run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
